name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Set your desired branch (e.g., main or master)
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19'  # Specify the Node.js version you want to use

      - name: Install dependencies
        run: npm install --legacy-peer-deps  # Or `yarn install` or `pnpm install` depending on your package manager

      - name: Build the project
        run: npm run build  # Run the build command for your project (Next.js default is `npm run build`)

      - name: Install Vercel CLI
        run: npm install -g vercel  # Install the Vercel CLI globally

      - name: Deploy to Vercel
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_SCOPE }} --confirm
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}  # Vercel Personal Access Token
          VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}  # Vercel Scope (optional, only if needed)
